Use Deploy Cache Service for Azure Xenial DevShips
wballard/starphleet pull request #407
Opened 2019-11-01 21:17 UTC by mikemartin1090

This PR is based on the work that @datfinesoul and @ddai1 completed here in [this ZenHub ticket](https://app.zenhub.com/workspaces/infrastructure---sre-5d92320acdc7cf0001013e24/issues/glg/metadevops-issues/213). The only difference IS that we want to merge these changes against the azure-xenial branch. NOT the asg branch since we are applying these to devships first.

2019-11-04 01:53 UTC, fearphage requested changes
A few suggestions to make the code more readable and easy to maintain. 

NOTE: Any changes should be copied to #406.

2019-11-04 01:53 UTC, fearphage commented on scripts/starphleet-git-synch
> +  if [[ -n "${GLG_DEPLOYCACHE_URL:-}" ]]; then
This is confusing. Why default a variable while you're checking to see whether or not it is empty?

```suggestion
  if [[ -n "$GLG_DEPLOYCACHE_URL" ]]; then
```

2019-11-04 01:53 UTC, fearphage commented on scripts/starphleet-git-synch
> +    read -r GIT_ORG GIT_REPO <<< $(echo $REMOTE | awk -F "[#/:]" '{gsub(/[.]git$/, "", $(NF)); print $(NF-1),$(NF)}')
We can simplify this a bit:

```suggestion
    read -r GIT_ORG GIT_REPO < <(awk -F '[:/.]' '{ print $3, $4 }' <<< $REMOTE)
```

2019-11-04 01:53 UTC, fearphage commented on scripts/starphleet-git-synch
> +      LATEST_REMOTE_SHA="$(echo "\"${DEPLOYCACHE_RESPONSE}\"" | (jq -r "." 2> /dev/null || echo -n "null"))"
What purpose is this line serving? Why do you need to pass quoted string to `jq --raw` just so it can remove the quotes that you intentionally put around it?

```suggestion
      LATEST_REMOTE_SHA="${DEPLOYCACHE_RESPONSE:-null}"
```

2019-11-04 01:53 UTC, fearphage commented on scripts/starphleet-git-synch
> +      # parsing failure will result is no update
```suggestion
      # parsing failure will result in no update
```

2019-11-04 01:53 UTC, fearphage commented on scripts/starphleet-git-synch
> +      curl -sSG -w '\n%{http_code}' \
Short key words are great for typing on the cli, but long keywords are great for reading. I personally don't know what any of these flags mean. One shouldn't have to research code to understand what it is doing. Add the full tags like the lines below.

2019-11-04 01:53 UTC, fearphage commented on scripts/starphleet-git-synch
> +    # explanation of awk: row separator no longer \n, field seperator is \n,
It's unexpected for the comments to be **after** the code they are referring to. Move these comments above line 56.

2019-11-04 16:26 UTC, fearphage commented
@datfinesoul This is mostly your code so I wanted to tag you and get your feedback on the code review comments.

2019-11-05 00:45 UTC, datfinesoul commented on scripts/starphleet-git-synch
> +  if [[ -n "${GLG_DEPLOYCACHE_URL:-}" ]]; then
Habit because I use `set -u` in most of my scripts.  Since starphleet doesn't have that as a global, we don't need it.

2019-11-05 00:58 UTC, datfinesoul commented on scripts/starphleet-git-synch
> +      LATEST_REMOTE_SHA="$(echo "\"${DEPLOYCACHE_RESPONSE}\"" | (jq -r "." 2> /dev/null || echo -n "null"))"
Safeguard in case the service doesn't not return a JSON safe string.  jq is used to validate and In that case of failure it returns null.

I thought i needed the double quotes, but I guess I might not.  But the jq check is intentional.

`echo -n "daada{" | jq --raw-input .` for example passes
`echo -n "daada{" | jq  .` fails, and produces what i was looking for

I'm not against changing it, but there was a reason for it when I wrote it.

2019-11-05 00:59 UTC, datfinesoul commented on scripts/starphleet-git-synch
> +      curl -sSG -w '\n%{http_code}' \
Sure

2019-11-05 01:01 UTC, datfinesoul commented on scripts/starphleet-git-synch
> +    read -r GIT_ORG GIT_REPO <<< $(echo $REMOTE | awk -F "[#/:]" '{gsub(/[.]git$/, "", $(NF)); print $(NF-1),$(NF)}')
Let me retest to see if it doesn't the same thing, but I'm all for the <<< $REMOTE, just sometimes forget about it.

2019-11-05 01:13 UTC, fearphage commented on scripts/starphleet-git-synch
> +  if [[ -n "${GLG_DEPLOYCACHE_URL:-}" ]]; then
Makes perfect sense. I wish I scripts were more strict that way.

2019-11-05 01:14 UTC, fearphage commented on scripts/starphleet-git-synch
> +    read -r GIT_ORG GIT_REPO <<< $(echo $REMOTE | awk -F "[#/:]" '{gsub(/[.]git$/, "", $(NF)); print $(NF-1),$(NF)}')
At the [top of this script](https://github.com/wballard/starphleet/blob/a938b35c0846fec9fdbe68803f2179248446dfe3/scripts/starphleet-git-synch#L12), the branch is stripped off the end so the `#` split isn't necessary.

2019-11-05 01:14 UTC, datfinesoul commented on scripts/starphleet-git-synch
> +    read -r GIT_ORG GIT_REPO <<< $(echo $REMOTE | awk -F "[#/:]" '{gsub(/[.]git$/, "", $(NF)); print $(NF-1),$(NF)}')
I'll change the <<< but the replacement code posted doesn't work for things like "https://github.com/sddsa/repo#master"

2019-11-05 01:18 UTC, fearphage commented on scripts/starphleet-git-synch
> +      LATEST_REMOTE_SHA="$(echo "\"${DEPLOYCACHE_RESPONSE}\"" | (jq -r "." 2> /dev/null || echo -n "null"))"
Interesting. I didn't know that would even work. If it serves a purpose, then go for it. I just didn't understand the line myself.

Is it special to our version of `jq`?

```shell
➜  sinon git:(master) ✗    echo -n "daada{" | jq -r .; echo $?1
parse error: Invalid numeric literal at line 1, column 6
41
➜  sinon git:(master) ✗    echo -n "daada{" | jq .; echo $?1
parse error: Invalid numeric literal at line 1, column 6
41
```

2019-11-05 01:23 UTC, datfinesoul commented
After convo in deploycache chat on Teams, I guess I'll make these changes in glg/starphleet for now, in the `fdt` branch there.

2019-11-05 02:28 UTC, datfinesoul commented
Re-creating and testing these changes in glg/starphleet#2 per conversation in Teams.

2019-11-05 06:37 UTC, datfinesoul commented
https://github.com/glg/starphleet/pull/4 replaces this PR

2019-11-05 15:32 UTC, fearphage commented on scripts/starphleet-git-synch
> +      LATEST_REMOTE_SHA="$(echo "\"${DEPLOYCACHE_RESPONSE}\"" | (jq -r "." 2> /dev/null || echo -n "null"))"
@datfinesoul How is that working?

2019-11-08 15:23 UTC, closed without merging